/** 仕上個別情報登録モーダル（EditWindow.xaml 相当） */
export type FinishCategoryEditFormData = {
  lotNo: number;
  organicClassCode: string;
  productNo: number | null;
  makeYear: string | null;
  itemName: string | null;
  count: string | null;
  workDate: string | null;
  lotName: string | null;
  processTypeCode: string;
  unitWeight: number | null;
  unitNumber: number | null;
  fractionWeightRaw: number | null;
  productQuantity: number;
  applicationRemarks: string | null;
  temperature: string;
  humidity: string;
  workStartHh: string;
  workStartMm: string;
  workEndHh: string;
  workEndMm: string;
  workBeforeCleaningStartHh: string;
  workBeforeCleaningStartMm: string;
  workBeforeCleaningEndHh: string;
  workBeforeCleaningEndMm: string;
  workEndCleaningStartHh: string;
  workEndCleaningStartMm: string;
  workEndCleaningEndHh: string;
  workEndCleaningEndMm: string;
  useDeviceUnit1: boolean;
  useDeviceUnit2: boolean;
  useDeviceUnit3: boolean;
  packingCase1: boolean;
  packingCase2: boolean;
  workBeforeCleaningChk: boolean;
  workAfterCleaningChk: boolean;
  deviceChk: boolean;
  operationChk: boolean;
  restChk: boolean;
  magnetCleaningChk: boolean;
  sp1UseChk: boolean;
  sp1Value1: string;
  sp1Value2a: string;
  sp1Value2b: string;
  sp1Value2c: string;
  sp1Value3a: string;
  sp1Value3b: string;
  sp1Value4: string;
  sp1Value5: string;
  sp1Value6a: string;
  sp1Value6b: string;
  sp2UseChk: boolean;
  sp2Value1: string;
  sp2Value2a: string;
  sp2Value2b: string;
  sp2Value2c: string;
  sp2Value2d: string;
  sp2Value3a: string;
  sp2Value3b: string;
  sp2Value4a: string;
  sp2Value4b: string;
  sp2Value5: string;
  etcValue1a: string;
  etcValue1b: string;
  etcValue1c: string;
  etcValue2a: string;
  etcValue2b: string;
  etcValue2c: string;
  etcValue2d: string;
  etcUseChk3a: boolean;
  etcUseChk3b: boolean;
  etcValue3: string;
  pickup1Name: string;
  pickup1Weight: string;
  pickup1Number: string;
  pickup1Fraction: string;
  pickup2Name: string;
  pickup2Weight: string;
  pickup2Number: string;
  pickup2Fraction: string;
  pickup3Name: string;
  pickup3Weight: string;
  pickup3Number: string;
  pickup3Fraction: string;
  pickup4Name: string;
  pickup4Weight: string;
  pickup4Number: string;
  pickup4Fraction: string;
  finishRemarks: string;
};

export type FinishCategoryUpsertPayload = {
  lot_no: number;
  sp1_use_chk: boolean | null;
  sp1_value_1: string | null;
  sp1_value_2a: string | null;
  sp1_value_2b: string | null;
  sp1_value_2c: string | null;
  sp1_value_3a: string | null;
  sp1_value_3b: string | null;
  sp1_value_4: string | null;
  sp1_value_5: string | null;
  sp1_value_6a: string | null;
  sp1_value_6b: string | null;
  sp2_use_chk: boolean | null;
  sp2_value_1: string | null;
  sp2_value_2a: string | null;
  sp2_value_2b: string | null;
  sp2_value_2c: string | null;
  sp2_value_2d: string | null;
  sp2_value_3a: string | null;
  sp2_value_3b: string | null;
  sp2_value_4a: string | null;
  sp2_value_4b: string | null;
  sp2_value_5: string | null;
  etc_value_1a: string | null;
  etc_value_1b: string | null;
  etc_value_1c: string | null;
  etc_value_2a: string | null;
  etc_value_2b: string | null;
  etc_value_2c: string | null;
  etc_value_2d: string | null;
  etc_use_chk3a: boolean | null;
  etc_use_chk3b: boolean | null;
  etc_value_3: string | null;
  pickup1_name: string | null;
  pickup1_weight: string | null;
  pickup1_number: string | null;
  pickup1_fraction: string | null;
  pickup2_name: string | null;
  pickup2_weight: string | null;
  pickup2_number: string | null;
  pickup2_fraction: string | null;
  pickup3_name: string | null;
  pickup3_weight: string | null;
  pickup3_number: string | null;
  pickup3_fraction: string | null;
  pickup4_name: string | null;
  pickup4_weight: string | null;
  pickup4_number: string | null;
  pickup4_fraction: string | null;
  remarks: string | null;
};
