import {
  emptyBeforeAfter,
  emptyTimeHm,
  emptyTimeRange,
  type PackageLotEditFormData
} from "./packageLotEditTypes";

/** 新規登録モーダル用の空フォーム */
export function createEmptyPackageLotEditForm(): PackageLotEditFormData {
  return {
    lotStatusCode: "1",
    organicClassPrefix: "",
    productNo: "",
    itemNo: "",
    productName: "",
    organicClass: "",
    workDate: "",
    temperature: "",
    humidity: "",
    useTeaItemNo1: "",
    useTeaItemName1: "",
    useTeaItemNo2: "",
    useTeaItemName2: "",
    partName: "",
    partLotNo1: "",
    outQuantity1: "",
    useQuantity1: "",
    completeQuantity: "",
    remQuantity1: "",
    partLotNo2: "",
    outQuantity2: "",
    useQuantity2: "",
    remQuantity2: "",
    partLotNo3: "",
    outQuantity3: "",
    useQuantity3: "",
    sampleQuantity: "",
    remQuantity3: "",
    failQuantity: "",
    packingStart: emptyTimeHm(),
    packingEnd: emptyTimeHm(),
    hp500No1Chk: false,
    hp500No2Chk: false,
    fr2Chk: false,
    fpgChk: false,
    ubaChk: false,
    cleaningBefore: emptyTimeRange(),
    cleaningAfter: emptyTimeRange(),
    liftCleaning: emptyBeforeAfter(),
    liftOperation: emptyBeforeAfter(),
    liftRem: emptyBeforeAfter(),
    packingFilter: emptyBeforeAfter(),
    packingSeal: emptyBeforeAfter(),
    packingConveyor: emptyBeforeAfter(),
    packingMagnet: emptyBeforeAfter(),
    packingOperation: emptyBeforeAfter(),
    packingRem: emptyBeforeAfter(),
    toolCleaning: emptyBeforeAfter(),
    uba3Cleaning: emptyBeforeAfter(),
    gradeNo: "",
    categorysRemarks: "",
    weightTestBefore: "",
    weightTestAfter: "",
    residualOxygenAm: "",
    residualOxygenPm: "",
    weightNo1: "",
    weightChk1: "",
    weightNo2: "",
    weightChk2: "",
    weightNo3: "",
    weightChk3: "",
    weightNo4: "",
    weightChk4: "",
    weightNo5: "",
    weightChk5: ""
  };
}
