/** 火入個別情報登録モーダル（EditWindow.xaml 相当） */
export type FirepanCategoryEditFormData = {
  lotNo: number;
  organicClassCode: string;
  productNo: number | null;
  makeYear: string | null;
  itemName: string | null;
  count: string | null;
  workDate: string | null;
  lotName: string | null;
  processTypeCode: string;
  unitWeight: number | null;
  unitNumber: number | null;
  fractionWeightRaw: number | null;
  productQuantity: number;
  applicationRemarks: string | null;
  temperature: string;
  humidity: string;
  workStartHh: string;
  workStartMm: string;
  workEndHh: string;
  workEndMm: string;
  workBeforeCleaningStartHh: string;
  workBeforeCleaningStartMm: string;
  workBeforeCleaningEndHh: string;
  workBeforeCleaningEndMm: string;
  workEndCleaningStartHh: string;
  workEndCleaningStartMm: string;
  workEndCleaningEndHh: string;
  workEndCleaningEndMm: string;
  useDeviceUnit1: boolean;
  useDeviceUnit2: boolean;
  useDeviceUnit3: boolean;
  packingCase1: boolean;
  packingCase2: boolean;
  workBeforeCleaningChk: boolean;
  workAfterCleaningChk: boolean;
  deviceChk: boolean;
  operationChk: boolean;
  restChk: boolean;
  magnetCleaningChk: boolean;
  firValue1: string;
  firValue2: string;
  firValue3a: string;
  firValue3b: string;
  firValue4a: string;
  firValue4b: string;
  firValue4c: string;
  firValue5: string;
  firValue6: string;
  firValue7: string;
  sensualTestColorBefore: string;
  sensualTestTasteBefore: string;
  sensualTestAromaBefore: string;
  sensualTestCommentBefore: string;
  sensualTestColorAfter: string;
  sensualTestTasteAfter: string;
  sensualTestAromaAfter: string;
  sensualTestCommentAfter: string;
  firepanRemarks: string;
};

export type FirepanCategoryUpsertPayload = {
  lot_no: number;
  fir_value_1: string | null;
  fir_value_2: string | null;
  fir_value_3a: string | null;
  fir_value_3b: string | null;
  fir_value_4a: string | null;
  fir_value_4b: string | null;
  fir_value_4c: string | null;
  fir_value_5: string | null;
  fir_value_6: string | null;
  fir_value_7: string | null;
  sensual_test_color_before: string | null;
  sensual_test_taste_before: string | null;
  sensual_test_aroma_before: string | null;
  sensual_test_comment_before: string | null;
  sensual_test_color_after: string | null;
  sensual_test_taste_after: string | null;
  sensual_test_aroma_after: string | null;
  sensual_test_comment_after: string | null;
  remarks: string | null;
};
