<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>TeaBlendReportHelper</RootNamespace>
    <AssemblyName>TeaBlendReportHelper</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <RapidReportLibDir>$(MSBuildProjectDirectory)\ThirdParty\RapidReport</RapidReportLibDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="systembase.barcode">
      <HintPath>$(RapidReportLibDir)\dotnetcore\systembase.barcode.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="systembase.json">
      <HintPath>$(RapidReportLibDir)\dotnetcore\systembase.json.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="systembase.report">
      <HintPath>$(RapidReportLibDir)\dotnetcore\systembase.report.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="systembase.report.renderer.gdi">
      <HintPath>$(RapidReportLibDir)\dotnetcore_gdi\systembase.report.renderer.gdi.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\*.rrpt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
